parameters:
    # Common hyperparameters
    name: 'FNN_warehouse'
    env_type: 'warehouse'
    time_horizon: 16
    num_frames: 1
    obs_size: 73
    # MAIN MODEL
    # Fully connected module
    fully_connected: true
    num_fc_layers: 2
    num_fc_units: [384, 128]
    # Convolutional module
    convolutional: false
    # Recurrent module
    recurrent: false

    # INFLUENCE MODEL
    influence: false
    
