parameters:
    # Common hyperparameters
    name: 'FNN_warehouse'
    env_type: 'warehouse'
    time_horizon: 8
    num_frames: 1
    obs_size: 73
    summary_frequency: 1.0e+4
    # MAIN MODEL
    # Fully connected module
    fully_connected: true
    num_fc_layers: 2
    num_fc_units: [512, 256]
    # Convolutional module
    convolutional: false
    # Recurrent module
    recurrent: false

    # INFLUENCE MODEL
    influence: false