parameters:
    # Common hyperparameters
    name: 'IAM_static'
    env_type: 'warehouse'
    time_horizon: 16
    obs_size: 37
    # MAIN MODEL
    # Fully connected module
    fully_connected: true
    num_fc_layers: 2
    num_fc_units: [256, 256]
    # Convolutional module
    convolutional: false
    # Recurrent module
    recurrent: false
    # INFLUENCE MODEL
    influence: true
    # Attention
    attention: false
    automatic_dpatch: false
    manual_dpatch: true
    # D-set
    inf_num_predictors: 37
    dset: [0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
           17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
           34, 35, 36]
    inf_num_rec_units: 128
    inf_seq_len: 16

