parameters:
    # Common hyperparameters
    name: 'InfluenceNet_warehouse'
    env_type: 'warehouse'
    time_horizon: 16
    num_workers: 1
    # MAIN MODEL
    # Fully connected module
    fully_connected: true
    num_fc_layers: 2
    num_fc_units: [256, 128]
    # Convolutional module
    convolutional: false
    # Recurrent module
    recurrent: false

    # INFLUENCE MODEL
    influence: true
    # Attention
    attention: false
    automatic_dpatch: false
    manual_dpatch: true
    # D-set
    inf_num_predictors: 49
    dset: [0, 1, 2, 3, 4, 5, 6, 7, 13, 14, 20, 21, 24, 27, 28, 
           34, 35, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 
           51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
           63, 64, 65, 66, 67, 68, 69, 70, 71, 72]
    inf_num_rec_units: 8
    inf_seq_len: 8
