parameters:
    # Common hyperparameters
    mode: 'train'
    load: true
    name: 'InfluenceNet_warehouse'
    algorithm: PPO
    port: 8000
    render: false
    env_type: 'warehouse'
    flicker: false
    max_steps: 1.0e+6
    max_episode_steps: 5.0e+3
    num_frames: 1
    num_epoch: 3
    gamma: 0.99
    lambda: 0.95
    learning_rate: 2.5e-4
    batch_size: 32
    memory_size: 128
    train_frequency: 1
    save_frequency: 1.0e+3
    summary_frequency: 1.0e+3
    tensorboard: true
    iteration: -1
    episode: 0
    frame_height: 5
    frame_width: 5

    # MAIN MODEL
    # Fully connected module
    fully_connected: true
    num_fc_layers: 1
    num_fc_units: [32]
    # Convolutional module
    convolutional: true
    num_conv_layers: 1
    num_filters: [32]
    kernel_sizes: [1]
    strides: [1]
    # Recurrent module
    recurrent: false
    num_rec_units: 256
    seq_len: 8

    # INFLUENCE MODEL
    influence: true
    # Attention
    attention: true
    num_att_units: [32]
    # This boxes now refer to the output of the last conv layer
    inf_box_height: [7]
    inf_box_width: [19]
    inf_box_center: [[0, 0]]
    inf_num_predictors: 1
    # Influence fully connected module
    inf_num_fc_layers: 0
    inf_num_fc_units: [128]
    # Influence recurrent module
    inf_num_rec_units: 256
    inf_seq_len: 4

    # PPO only
    num_workers: 8
    beta: 1.0e-2
    epsilon: 0.1
    time_horizon: 128
    c1: 1
