parameters:
    # Common hyperparameters
    name: 'InfluenceNet_warehouse'
    env_type: 'warehouse'
    time_horizon: 16
    # MAIN MODEL
    # Fully connected module
    fully_connected: true
    num_fc_layers: 2
    num_fc_units: [512, 256]
    # Convolutional module
    convolutional: false
    # Recurrent module
    recurrent: false

    # INFLUENCE MODEL
    influence: true
    # Attention
    attention: false
    automatic_dpatch: false
    manual_dpatch: true
    # D-set
    inf_num_predictors: 25
#   dset: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ,10, 11, 12, 
#          13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23
#          24, 25, 20, 21, 24, 27, 28, 
#          34, 35, 41, 42, 43, 44, 45, 46, 47, 48, 
    dset: [0, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
           63, 64, 65, 66, 67, 68, 69, 70, 71, 72]
    inf_num_rec_units: 32
    inf_seq_len: 8
