parameters:
    # Common hyperparameters
    name: 'IAM_dynamic_minigrid'
    env_type: 'minigrid'
    scene: 'MiniGrid-RedBlueDoors-8x8-v0'
    max_steps: 5.0e+5
    frame_height: 7
    frame_width: 7
    num_frames: 1
    summary_frequency: 1.0e+4
    obs_type: 'vector'
    obs_size: 49
    epsilon: 0.2
    time_horizon: 32
    learning_rate: 1.0e-3

    # MAIN MODEL
    # Fully connected module
    fully_connected: true
    num_fc_layers: 1
    num_fc_units: [256, 128]
    # Convolutional module
    convolutional: false
    num_conv_layers: 2
    # num_filters: [32, 64, 64]
    # kernel_sizes: [8, 4, 3]
    # strides: [4, 2, 1]
    num_filters: [16, 32]
    kernel_sizes: [2, 2]
    strides: [1, 1]
    # Recurrent module
    recurrent: false

    # INFLUENCE MODEL
    influence: true
    # Attention
    attention: true
    num_heads: 1
    num_att_units: [32]
    # Influence recurrent module
    inf_num_rec_units: 64
    inf_seq_len: 4

