parameters:
    # Common hyperparameters
    name: 'RNN_minigrid'
    env_type: 'minigrid'
    scene: 'MiniGrid-RedBlueDoors-8x8-v0'
    max_steps: 5.0e+6
    frame_height: 56
    frame_width: 56
    obs_type: 'image'

    # MAIN MODEL
    # Fully connected module
    fully_connected: false
    # Convolutional module
    convolutional: true
    num_conv_layers: 3
    num_filters: [32, 64, 64]
    kernel_sizes: [8, 4, 3]
    strides: [4, 2, 1]
    # Recurrent module
    recurrent: true
    num_rec_units: 512
    seq_len: 4

    # INFLUENCE MODEL
    influence: false

