parameters:
    # Common hyperparameters
    name: 'RNN_minigrid'
    env_type: 'minigrid'
    scene: 'MiniGrid-RedBlueDoors-8x8-v0'
    max_steps: 5.0e+5
    frame_height: 7
    frame_width: 7
    num_frames: 1
    summary_frequency: 1.0e+4
    obs_type: 'vector'
    obs_size: 49
    epsilon: 0.2
    time_horizon: 64
    learning_rate: 1.0e-3

    # MAIN MODEL
    # Fully connected module
    fully_connected: true
    num_fc_layers: 1
    num_fc_units: [256]
    # Convolutional module
    convolutional: false
    num_conv_layers: 2
    # num_filters: [32, 64, 64]
    # kernel_sizes: [8, 4, 3]
    # strides: [4, 2, 1]
    num_filters: [16, 32]
    kernel_sizes: [2, 2]
    strides: [1, 1]
    # Recurrent module
    recurrent: true
    num_rec_units: 128
    seq_len: 4

    # INFLUENCE MODEL
    influence: false
    

