parameters:
    # Common hyperparameters
    mode: 'train'
    name: 'FNN'
    env_type: 'sumo' # 'atari', 'SUMO', or 'gridworld'
    scene: 'loop_network'
    max_steps: 1.0e+6
    obs_type: vector
    obs_size: 30
    time_horizon: 128
    num_epoch: 4
    max_episode_steps: 250
    batch_size: 32
    summary_frequency: 5.0e+4
    beta: 0.1

    # MAIN MODEL
    # Fully connected module
    fully_connected: true
    num_fc_layers: 2
    num_fc_units: [256, 160]
    # Convolutional module
    convolutional: false
    # Recurrent module
    recurrent: false

    # INFLUENCE MODEL
    influence: false

