parameters:
    # Common hyperparameters
    mode: 'train'
    name: 'FNN'
    env_type: 'sumo' # 'atari', 'SUMO', or 'gridworld'
    scene: 'loop_network'
    flicker: false
    max_steps: 5.0e+5
    num_frames: 1
    obs_type: image
    frame_height: 84
    frame_width: 84
    num_workers: 8
    beta: 5.0e-3
    epsilon: 0.2
    time_horizon: 128
    num_epoch: 4
    
    # MAIN MODEL
    # Fully connected module
    fully_connected: true
    num_fc_layers: 1
    num_fc_units: [256]
    # Convolutional module
    convolutional: true
    num_conv_layers: 3
    num_filters: [32, 64, 64]
    kernel_sizes: [8, 4, 3]
    strides: [4, 2, 1]
    # Recurrent module
    recurrent: false

    # INFLUENCE MODEL
    influence: false

