parameters:
    # Common hyperparameters
    mode: 'train'
    name: 'manual_dpatch'
    env_type: 'sumo' # 'atari', 'SUMO', or 'gridworld'
    scene: 'loop_network'
    max_steps: 1.0e+6
    num_frames: 1
    obs_type: image
    frame_height: 15
    frame_width: 15
    time_horizon: 128
    num_epoch: 4
    obs_type: 'vector'
    obs_size: 30
    
    # MAIN MODEL
    # Fully connected module
    fully_connected: true
    num_fc_layers: 2
    num_fc_units: [128, 64]
    # Convolutional module
    convolutional: false
    num_conv_layers: 2
    num_filters: [16, 32]
    kernel_sizes: [4, 2]
    strides: [2, 1]
    # Recurrent module
    recurrent: false

    # INFLUENCE MODEL
    influence: true
    # Attention
    attention: false
    automatic_dpatch: false
    manual_dpatch: true
    # D-set
    inf_num_predictors: 4
    dset: [13, 14, 28, 29]
    # Influence recurrent module
    inf_num_rec_units: 8
    inf_seq_len: 32

